name: root
dependencies:
- _license=1.1=py27_0
- abstract-rendering=0.5.1=np110py27_0
- alabaster=0.7.7=py27_0
- anaconda=2.4.0=np110py27_0
- anaconda-client=1.1.0=py27_0
- argcomplete=1.0.0=py27_1
- astropy=1.0.5=np110py27_1
- babel=2.2.0=py27_0
- backports_abc=0.4=py27_0
- bcolz=0.9.0=np19py27_0
- beautiful-soup=4.3.2=py27_0
- beautifulsoup4=4.4.1=py27_0
- binstar=0.11.0=py27_0
- bitarray=0.8.1=py27_0
- blaze-core=0.8.3=py27_0
- blz=0.6.2=np19py27_1
- bokeh=0.10.0=py27_0
- boto=2.38.0=py27_0
- bottleneck=1.0.0=np110py27_0
- cairo=1.12.18=6
- cdecimal=2.3=py27_0
- certifi=2015.9.6.2=py27_0
- cffi=1.2.1=py27_0
- clyent=0.4.0=py27_0
- colorama=0.3.3=py27_0
- conda=3.19.1=py27_0
- conda-build=1.14.1=py27_0
- conda-env=2.4.5=py27_0
- configobj=5.0.6=py27_0
- cryptography=1.0.2=py27_0
- curl=7.45.0=0
- cycler=0.9.0=py27_0
- cython=0.23.4=py27_0
- cytoolz=0.7.4=py27_0
- datashape=0.4.7=np110py27_1
- decorator=4.0.6=py27_0
- dill=0.2.4=py27_0
- docutils=0.12=py27_0
- dynd-python=0.6.5=np19py27_0
- enum34=1.1.2=py27_0
- fastcache=1.0.2=py27_0
- flask=0.10.1=py27_1
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.9=py27_0
- grin=1.2.1=py27_1
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- idna=2.0=py27_0
- illumiprocessor=2.0.7=py27_1
- ipaddress=1.0.14=py27_0
- ipykernel=4.2.2=py27_0
- ipyparallel=4.1.0=py27_0
- ipyrad=0.1.37=6
- ipython=4.0.0=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython-qtconsole=4.0.1=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jdcal=1.0=py27_0
- jedi=0.9.0=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- libdynd=0.6.5=0
- libffi=3.0.13=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- llvmlite=0.8.0=py27_0
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- mistune=0.7.1=py27_0
- mkl=11.3.1=0
- mock=1.0.1=py27_0
- mpi4py=2.0.0=py27_0
- mpich2=1.4.1p1=0
- multipledispatch=0.4.8=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.10=py27_0
- nltk=3.1=py27_0
- nose=1.3.7=py27_0
- notebook=4.1.0=py27_0
- numba=0.23.1=np110py27_0
- numexpr=2.4.4=np110py27_0
- numpy=1.10.4=py27_0
- odo=0.3.4=py27_0
- openblas=0.2.14=3
- openpyxl=2.2.6=py27_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py27_0
- patchelf=0.6=0
- path.py=8.1.2=py27_1
- patsy=0.4.0=np110py27_0
- pep8=1.6.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_1
- pip=8.0.2=py27_0
- pixman=0.32.6=0
- ply=3.8=py27_0
- psutil=3.4.2=py27_0
- ptyprocess=0.5=py27_0
- py=1.4.30=py27_0
- py2cairo=1.10.0=py27_2
- pyasn1=0.1.9=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.14=py27_0
- pycrypto=2.6.1=py27_0
- pycurl=7.19.5.1=py27_3
- pyflakes=1.0.0=py27_0
- pygments=2.1=py27_0
- pyopenssl=0.15.1=py27_1
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- pytest=2.8.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_1
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py27_0
- requests=2.9.1=py27_0
- rope=0.9.4=py27_1
- runipy=0.1.3=py27_0
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.16.1=np110py27_0
- scipy=0.17.0=np110py27_1
- seaborn=0.6.0=np110py27_0
- setuptools=19.6.2=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.1=py27_0
- sphinx=1.3.5=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=2.3.7=py27_1
- spyder-app=2.3.7=py27_0
- sqlalchemy=1.0.9=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- sympy=0.7.6.1=py27_0
- system=5.8=2
- terminado=0.5=py27_1
- theano=0.7.0=np110py27_0
- tk=8.5.18=0
- toolz=0.7.4=py27_0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- trimmomatic=0.32=1
- ujson=1.33=py27_0
- unicodecsv=0.14.1=py27_0
- util-linux=2.21=0
- werkzeug=0.10.4=py27_0
- wheel=0.26.0=py27_1
- xlrd=0.9.4=py27_0
- xlsxwriter=0.7.7=py27_0
- xlwt=1.0.0=py27_0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - blaze==0.8.3
  - colormath==2.1.1
  - dendropy==4.0.3
  - ete2==2.3.10
  - illumiprocessor (/home/deren/local/src/illumiprocessor_local)==2.0.6
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - pbr==1.8.1
  - pockets==0.2.4
  - pymc3==3.0
  - rpy2==2.7.2
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-napoleon==0.3.11
  - stevedore==1.9.0
  - tables==3.2.2
  - tapir==1.0
  - toyplot==0.8.0
  - virtualenv==13.1.2
  - virtualenv-clone==0.2.6
  - virtualenvwrapper==4.7.1

